name: core
description: Dart package which manages the core functionality of the app.
publish_to: none

environment:
  sdk: ^3.7.0
dependencies:
  http: ^1.4.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^4.2.1
dev_dependencies:
  json_serializable: ^6.9.5
  build_runner: ^2.4.15


