name: core
description: Dart package which manages the core functionality of the app.
publish_to: none

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  isar_flutter_libs: ^4.0.0-dev.14
  hive: ^4.0.0-dev.2
  user_repository:
    path: ../user_repository
dev_dependencies:
  json_serializable:  ^6.8.0
  build_runner: ^2.4.15


